{"ast":null,"code":"'use strict';\n\nconst pFinally = require('p-finally');\n\nclass TimeoutError extends Error {\n  constructor(message) {\n    super(message);\n    this.name = 'TimeoutError';\n  }\n\n}\n\nconst pTimeout = (promise, milliseconds, fallback) => new Promise((resolve, reject) => {\n  if (typeof milliseconds !== 'number' || milliseconds < 0) {\n    throw new TypeError('Expected `milliseconds` to be a positive number');\n  }\n\n  if (milliseconds === Infinity) {\n    resolve(promise);\n    return;\n  }\n\n  const timer = setTimeout(() => {\n    if (typeof fallback === 'function') {\n      try {\n        resolve(fallback());\n      } catch (error) {\n        reject(error);\n      }\n\n      return;\n    }\n\n    const message = typeof fallback === 'string' ? fallback : `Promise timed out after ${milliseconds} milliseconds`;\n    const timeoutError = fallback instanceof Error ? fallback : new TimeoutError(message);\n\n    if (typeof promise.cancel === 'function') {\n      promise.cancel();\n    }\n\n    reject(timeoutError);\n  }, milliseconds); // TODO: Use native `finally` keyword when targeting Node.js 10\n\n  pFinally( // eslint-disable-next-line promise/prefer-await-to-then\n  promise.then(resolve, reject), () => {\n    clearTimeout(timer);\n  });\n});\n\nmodule.exports = pTimeout; // TODO: Remove this for the next major release\n\nmodule.exports.default = pTimeout;\nmodule.exports.TimeoutError = TimeoutError;","map":null,"metadata":{},"sourceType":"script"}